### ISSUE TITLE
Images not displaying the filehub itself

### ISSUE THREAD

**Issue by maciejduk** [scthakuri/django-filehub#1]
Hi! Thanks for uploading this project. I find the interface actually belongs to the year we're living in compared to `django-filebrowser`.

I am having troubles with images not showing their content in the filehub itself:

![Image](https://github.com/user-attachments/assets/62f4b3b5-bf6f-43e9-a361-faaf4dc7edd6)

They are showing OK inside TinyMCE editor as well as website:
![Image](https://github.com/user-attachments/assets/6bbf3283-b12f-4b44-a5e2-986fb7439d14)
![Image](https://github.com/user-attachments/assets/323799b5-ec18-4614-85a9-d565ba37b46a)

Any ideas what this could be?

My settings are as below:

### settings.py
```python
DEBUG = True
INSTALLED_APPS = [
    'pages.apps.PagesConfig',
    'projects.apps.ProjectsConfig',
    'news.apps.NewsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'filehub'

]

MEDIA_ROOT = BASE_DIR / "uploads/"
MEDIA_URL = "media/"

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static_nondjango"
]
```

### urls.py
```
urlpatterns = [
    path('admin/', include('filehub.urls')),
    path('admin/', admin.site.urls),
    # path('polls/', include('polls.urls')),
    path('', include('pages.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('news/', include('news.urls')),
]
```

Any help will be appreciated. I am testing locally using standard `python manage.py runserver`.

**Comment by scthakuri** [comment]
Thanks for your feedback!

I'm currently looking into the issue with images not displaying in FileHub. I expect to have a fix for this today. Once it's resolved, I'll update this thread.

**Comment by scthakuri** [comment]
This issue has been successfully resolved in version [`3.1.0`](https://pypi.org/project/django-filehub/). Please update to the latest version to apply the fix.

If you encounter any further issues, feel free to reopen this ticket or create a new one.

**Comment by maciejduk** [comment]
Hi, I've tested and upgrade to 3.1.0, this caused the following error being thrown:

![Image](https://github.com/user-attachments/assets/c9cef723-8244-4086-9a89-8575c132a70a)

fixed it by installing the dependency
```bash
python -m pip install standard-imghdr
```

The error is gone but the images are still not showing in the browser (I've made sure to upload new items):

![Image](https://github.com/user-attachments/assets/23c98374-53f0-4c71-b70a-040667000650)

But they are showing correctly in actual content and no further errors on the console.

**Comment by maciejduk** [comment]
@scthakuri hi is there any update on this? I cannot reopen the issue due to no perms :-(
